openapi: 3.0.3
info:
  title: STD23010 - TD_final_part1
  version: '1.0.2'
servers:
  - url: https://localhost.std23010.com
paths:

  /competition:
        get:
      tags:
        -list of competitions       
      summary: Get the list of competitions
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: the list of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'

    post:
      tags:
        -competition
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        '200':
          description: The Competition is create

  /teams:
    get:
      tags:
        -list of teams
      summary: Get the list of teams
      parameters:
        - name: teamName
          in: query
          required: false
          schema:
            type: string
            description: Filter teams by their name
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'

    post:
      tags:
        -team
      summary: Create new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Team created 

  /teams/{teamId}/players:
    get:
      tags:
        -list of players for specific team
      summary: Get list of players for specific team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
        - name: playerName
          in: query
          required: false
          schema:
            type: string
            description: Filter players by their name
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'

  /teams/{teamId}/players:
    post:
      tags:
        -player to a team
      summary: Add players to a team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Players add to team   

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
        countryOrContinent:
          type: string

    Team:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        strongFoot:
          type: string
          enum: [Left, Right]                       
      
